#!/usr/bin/env bash
# Fast path to the OHOS buildenv image: reuse the toolchain already built in
# the local Docker volumes (Qt for OHOS, vcpkg arm64-ohos) and the command-
# line tools directory, instead of rebuilding Qt from scratch (2-4 h, see
# Dockerfile for that reproducible-but-slow path).
#
# Prereqs on the build machine (see docs/ohos/HANDOVER_CODEX.md):
#   - docker volumes: mixxx-ohos-qt-out, mixxx-ohos-vcpkg
#   - HarmonyOS command-line tools at F:/command-line-tools (override: $CLT_DIR)
#   - image winehua-dev (the same base the build container uses)
#   - docker login ghcr.io (account with write access to the org packages)
#
# Usage:
#   bash packaging/ohos/ci/build-image-from-volumes.sh [image-tag]
# Default tag: ghcr.io/pomelotechlabs/mixxx/buildenv-ohos:latest
#
# Autonomously generated by an AI Agent.

set -euo pipefail

TAG="${1:-ghcr.io/pomelotechlabs/mixxx/buildenv-ohos:latest}"
CLT_DIR="${CLT_DIR:-F:/command-line-tools}"
QT_OUT_VOLUME="${QT_OUT_VOLUME:-mixxx-ohos-qt-out}"
VCPKG_VOLUME="${VCPKG_VOLUME:-mixxx-ohos-vcpkg}"

echo "==> seeding a temp container from the local volumes"
MSYS_NO_PATHCONV=1 docker rm -f mixxx-buildenv-seed >/dev/null 2>&1 || true
MSYS_NO_PATHCONV=1 docker run --name mixxx-buildenv-seed \
  -v "${QT_OUT_VOLUME}:/mnt/qt-out:ro" \
  -v "${VCPKG_VOLUME}:/mnt/vcpkg:ro" \
  -v "${CLT_DIR}:/mnt/harmony:ro" \
  winehua-dev bash -c '
    set -eux
    mkdir -p /seed/vcpkg/vcpkg
    cp -a /mnt/harmony /seed/harmony
    cp -a /mnt/qt-out /seed/out
    cp -a /mnt/vcpkg/vcpkg/installed /seed/vcpkg/vcpkg/installed
    cp -a /mnt/vcpkg/VCPKG_COMMIT.txt /seed/vcpkg/ 2>/dev/null || true
    du -sh /seed/harmony /seed/out /seed/vcpkg
  '
trap "MSYS_NO_PATHCONV=1 docker rm -f mixxx-buildenv-seed >/dev/null 2>&1 || true" EXIT
docker commit mixxx-buildenv-seed mixxx-ohos-buildenv:seed >/dev/null

echo "==> assembling ${TAG}"
MSYS_NO_PATHCONV=1 docker build -t "${TAG}" -f - . <<'DOCKERFILE'
FROM mixxx-ohos-buildenv:seed
RUN mkdir -p /data/vcpkg/vcpkg /apps /data/src /data/mixxx-build \
 && mv /seed/harmony /apps/harmony \
 && mv /seed/out /data/out \
 && mv /seed/vcpkg/vcpkg/installed /data/vcpkg/vcpkg/installed \
 && mv /seed/vcpkg/VCPKG_COMMIT.txt /data/vcpkg/ 2>/dev/null || true \
 && rm -rf /seed \
 && test -f /apps/harmony/sdk/default/openharmony/native/build/cmake/ohos.toolchain.cmake \
 && test -d /data/out/qt-ohos/usr/lib/cmake/Qt6 \
 && test -d /data/vcpkg/vcpkg/installed/arm64-ohos/usr/lib \
 && /apps/harmony/bin/hvigorw --version
ENV OHOS_SDK_ROOT=/apps/harmony/sdk/default/openharmony \
    DEVECO_SDK_HOME=/apps/harmony/sdk
DOCKERFILE

echo "==> done: ${TAG}"
docker images "${TAG%%:*}" --format '{{.Repository}}:{{.Tag}} {{.Size}}' | head -3

# Autonomously generated by an AI Agent.
