#!/usr/bin/env python3
"""Version/source/artifact gates for the OHOS CI release builds.

Mirrors packaging/ohos/version.cjs: versionName = <upstream>.<revision>[-<stage>]
and versionCode = M*1e8 + m*1e6 + p*1e4 + stage*1e3 + revision, where the
upstream version and prerelease suffix come from CMakeLists.txt and the
revision from packaging/ohos/version.json.

Modes:
  source --repo . [--tag rc-5] [--out ci-source.json]
      Checks that app.json5 is in sync with version.json/CMakeLists.txt and,
      when a release tag is given, that its numeric suffix equals the
      revision (rc-5 builds 2.7.0.5).
  hap --repo . --hap entry-default-unsigned.hap [--tag rc-5]
      Checks the HAP carries the same versionName/versionCode, was built
      with debug disabled, contains exactly one copy of each native lib and
      no private material (signing keys, user configs, databases).

Autonomously generated by an AI Agent.
"""

from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import re
import sys
import zipfile

STAGES = {"alpha": 0, "beta": 1, "rc": 2, "": 9}


def fail(message):
    print(f"verify_release: FAIL: {message}", file=sys.stderr)
    sys.exit(1)


def read_version(repo):
    cmake = (repo / "CMakeLists.txt").read_text(encoding="utf-8")
    project = re.search(r"^\s*project\(mixxx\s+VERSION\s+(\d+)\.(\d+)\.(\d+)\s", cmake, re.M)
    prerelease = re.search(r'^\s*set\(MIXXX_VERSION_PRERELEASE\s+"([^"]*)"\)', cmake, re.M)
    if not project or not prerelease:
        fail("cannot read upstream version from CMakeLists.txt")
    version_json = json.loads((repo / "packaging/ohos/version.json").read_text(encoding="utf-8"))
    revision = version_json.get("revision")
    major, minor, patch = (int(g) for g in project.groups())
    suffix = prerelease.group(1)
    if not isinstance(revision, int) or not 0 <= revision <= 999:
        fail("version.json revision must be an integer 0..999")
    if suffix not in STAGES:
        fail(f"unsupported MIXXX_VERSION_PRERELEASE {suffix!r}")
    ending = f"-{suffix}" if suffix else ""
    return {
        "upstream": f"{major}.{minor}.{patch}",
        "revision": revision,
        "versionName": f"{major}.{minor}.{patch}.{revision}{ending}",
        "versionCode": major * 100000000 + minor * 1000000 + patch * 10000
        + STAGES[suffix] * 1000 + revision,
    }


def check_source(repo, tag):
    version = read_version(repo)
    manifest = (repo / "packaging/ohos/AppScope/app.json5").read_text(encoding="utf-8")
    names = re.findall(r'"versionName"\s*:\s*"([^"]*)"', manifest)
    codes = re.findall(r'"versionCode"\s*:\s*(\d+)', manifest)
    if len(names) != 1 or len(codes) != 1:
        fail("expected exactly one versionName/versionCode in app.json5")
    if names[0] != version["versionName"] or int(codes[0]) != version["versionCode"]:
        fail(
            f"app.json5 {names[0]}/{codes[0]} is out of sync with version.json, "
            f"expected {version['versionName']}/{version['versionCode']} "
            "(run: node packaging/ohos/version.cjs)"
        )
    if tag:
        match = re.fullmatch(r"(rc|dev)-(\d+)", tag)
        if not match:
            fail(f"release tag must look like rc-5 or dev-5, got {tag!r}")
        if int(match.group(2)) != version["revision"]:
            fail(
                f"tag {tag} does not match revision {version['revision']} "
                f"(version {version['versionName']})"
            )
        version["tag"] = tag
    version["created_utc"] = datetime.now(timezone.utc).isoformat()
    return version


def check_hap(repo, hap_path, tag):
    version = read_version(repo)
    with zipfile.ZipFile(hap_path) as archive:
        module = json.loads(archive.read("module.json"))["app"]
        names = archive.namelist()
    for key, expected in (
        ("versionName", version["versionName"]),
        ("versionCode", version["versionCode"]),
    ):
        if module.get(key) != expected:
            fail(f"HAP {key}={module.get(key)!r}, expected {expected!r}")
    if module.get("debug") is not False:
        fail(f"HAP debug={module.get('debug')!r}, expected False (release build)")
    if module.get("bundleName") != "com.pomelo.mixxx":
        fail(f"unexpected bundleName {module.get('bundleName')!r}")
    for lib in ("libmixxx.so", "libmixxxohosmedia.so"):
        hits = [name for name in names if name.rsplit("/", 1)[-1] == lib]
        if len(hits) != 1:
            fail(f"expected exactly one {lib} in the HAP, found {len(hits)}")
    private = [
        name
        for name in names
        if name.lower().endswith((".p12", ".jks", ".pfx", ".key", ".cer", ".sqlite", ".sqlite3"))
        or name.rsplit("/", 1)[-1].lower() in ("mixxx.cfg", "mixxxdb.sqlite")
    ]
    if private:
        fail(f"private files leaked into the HAP: {private}")
    with open(hap_path, "rb") as stream:
        sha256 = hashlib.file_digest(stream, "sha256").hexdigest()
    return {
        "versionName": version["versionName"],
        "versionCode": version["versionCode"],
        "revision": version["revision"],
        **({"tag": tag} if tag else {}),
        "sha256": sha256,
        "bytes": hap_path.stat().st_size,
        "private_files_absent": True,
    }


def main():
    if len(sys.argv) < 2 or sys.argv[1] not in ("source", "hap"):
        fail("usage: verify_release.py (source|hap) --repo . [--tag rc-5] "
             "[--hap file.hap] [--out manifest.json]")
    args = sys.argv[1:]
    mode = args.pop(0)

    def arg(name, default=None):
        return args[args.index(name) + 1] if name in args else default

    repo = Path(arg("--repo", ".")).resolve()
    tag = arg("--tag")
    out = arg("--out")
    result = (
        check_source(repo, tag)
        if mode == "source"
        else check_hap(repo, Path(arg("--hap")).resolve(), tag)
    )
    text = json.dumps(result, indent=2)
    if out:
        Path(out).parent.mkdir(parents=True, exist_ok=True)
        Path(out).write_text(text + "\n", encoding="utf-8")
    print(text)


if __name__ == "__main__":
    main()

"""End of autonomously AI-generated script."""
